### ISSUE TITLE
Features project boxes alignment/size

### ISSUE THREAD

**Issue by santiagozky** [Netcentric/netcentric.github.io#18]
It would be great if we could make those boxes either the same size or vertically aligned at the top.

Low priority

<img width="1195" alt="Screenshot 2022-01-13 at 5 32 34 PM" src="https://user-images.githubusercontent.com/1405393/149370270-ec0231c4-c4cc-4a09-b811-aa6e979d6e70.png">

**Comment by quicoto** [comment]
Will align at the top as the fastest solution for now.

Thank you
