### ISSUE TITLE
favicon color in safari looks wrong.

### ISSUE THREAD

**Issue by santiagozky** [Netcentric/netcentric.github.io#19]
Not sure why, but the favicon icon in Safari 15 looks in a pale blue instead of our usual purple.

<img width="334" alt="Screenshot 2022-01-13 at 5 37 24 PM" src="https://user-images.githubusercontent.com/1405393/149371098-4997e19b-0679-4b37-b293-882e919e65bf.png">

**Comment by quicoto** [comment]
Done, thanks
